### ISSUE TITLE
Add VRF to an existing template associated with cloud site

### ISSUE THREAD

**Issue by fwardzic** [CiscoDevNet/ansible-mso#137]
When adding VRF to a template which is associated with cloud site, we cannot use module: mso_schema_template_vrf, as it complains that region and VPC CIDR has to be specified. 
The only way to add new VRF is to add VRF to new template not associated with any site,  and then associate it with cloud site. After that we can configure region, CIDR and other site specific settings using other modules like: mso_schema_site_vrf_region_cidr. 
This is good approach for first VRF and new template. In this model we cannot add more VRFs later when template will be already associated with cloud site.

**Comment by lhercot** [comment]
Hi @fwardzic,

This is currently an API limitation that we cannot easily fix from the collection side.
You can use different templates per VRF to get around it today but it is not great. 
We are working on improving the API so that we can do partial edits without having to do both the template level change and the site level change at the same time.

If you still want to add it to an existing one, you will be able to do it with the mso_rest but you will need to wrap it with some ansible logic to make it idempotent.

**Comment by fwardzic** [comment]
Thank you Lionel,
Could you advice where to find mso_rest module ?

**Comment by lhercot** [comment]
It is currently in review in this PR: https://github.com/CiscoDevNet/ansible-mso/pull/132
Once the review is done, we will merge it and it will then be part of the subsequent release.

I hope to get this done in the next 2 weeks but might be sooner. Don't hesitate to subscribe to the issue #112 if you want to be kept in the loop when we close that PR.

**Comment by lhercot** [comment]
This is fixed in the v1.2.0 but you will need to use MSO 3.3 as this is related to an API issue.
In MSO 3.3, a new validate flag is introduced in the API which disable the validations so we can add part of the schema independently from each other. User need to make sure they have all the right parts applied before pushing the change.

We have added the validate=false option in all PATCH calls in v1.2.0 and are planning to add a module to validate if all checks are passing as part of #197
