### ISSUE TITLE
[mso_schema_template_anp_epg] Unable to delete epg after a static port has been created

### ISSUE THREAD

**Issue by patrickspaans** [CiscoDevNet/ansible-mso#145]
Normally, creating an ANP EPG and then deleting it works fine. However, once a static port has been assigned to this EPG, you are unable to delete the EPG even after the static port has been deleted again. I then get the following error message:

`MSO Error 142: Invalid Reference: Unable to find EPG 'EpgRef(5fcf8ef836000028f111498e,testtemplate,testanp,testepg)
`

By removing the template-site association where the static port was assigned to, I'm once again able to delete the EPG as usual. On the MSO, the static ports have indeed been removed after removing it, so I don't think that's the issue.

Here a few playbooks and their outputs to showcase this:

Playbook without using static ports, works as intended, as well as output:
[epg_no_static_port.zip](https://github.com/CiscoDevNet/ansible-mso/files/5660025/epg_no_static_port.zip)

Playbook while using static ports, which fails, as well as output:
[epg_with_static_port.zip](https://github.com/CiscoDevNet/ansible-mso/files/5660020/epg_with_static_port.zip)

In the zip folder, I've included the output normally as well as when using -vvvv.

I'm using V1.0.1 of the ansible modules, and version 3.0(3l) of the MSO.

**Comment by anvitha-jain** [comment]
Hi @patrickspaans,

In the playbook provided, 
- the site is added to schema( template ). 
- Since the API uses PATCH request, mso_schema_template_anp_epg attempts to remove EPG from template level, and not   from site level. This is the reason for the above error.
- To resolve this error, remove EPG from site level first ( using mso_schema_site_anp_epg ) and then remove it from template level.

This should resolve the issue.

**Comment by patrickspaans** [comment]
Thank you, I hadn't considered that I would need the mso_schema_site_anp_epg to delete it.
